Epic statistic
MaxCode2023/iOS-FakeNFT-StarterProject-Public pull request #68
Opened 2023-06-25 03:31 UTC by MaxCode2023

2023-06-25 20:47 UTC, DmitriiMM requested changes

2023-06-25 20:47 UTC, DmitriiMM commented on FakeNFT/Scenes /Statistic/RatingProfile/RatingProfileViewController.swift
> +        nftCollectionLabel.text = "Коллекция NFT"
Давай добавим файл Localizable.strings на один язык
Пригодится в будущем)

2023-06-25 20:47 UTC, DmitriiMM commented on FakeNFT/Scenes /Statistic/RatingProfile/RatingProfileViewController.swift
> +            navigationController?.pushViewController(vc, animated: true)
Большой вопрос!
Не могу добраться до экрана с коллекцией нфт, так как у любого пользователя из таблицы рейтинга 0 нфт в коллекции. возможно из апи нужно брать не user, а profile?

2023-06-25 20:47 UTC, DmitriiMM commented on FakeNFT/Scenes /Statistic/RatingProfile/RatingProfileViewController.swift
> +    private let nftCollectionView = UIView()
nftCollectionView сто процентов нужно переименовать

2023-06-25 20:47 UTC, DmitriiMM commented on FakeNFT/Scenes /Statistic/RatingProfile/RatingProfileViewController.swift
> +            nftCollectionCountLabel.bottomAnchor.constraint(equalTo: nftCollectionView.bottomAnchor, constant: -16),
два лейбла обрезаются по низу. можно изменить констрейнты
<img width="326" alt="Снимок экрана 2023-06-25 в 22 20 04" src="https://github.com/MaxCode2023/iOS-FakeNFT-StarterProject-Public/assets/86566994/b2fb5e5a-cc2f-4b1c-8a01-dab74901fa35">

2023-06-26 04:54 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/RatingProfile/RatingProfileViewController.swift
> +            navigationController?.pushViewController(vc, animated: true)
У большинства пользователей 0 нфт, но если покликать можно найти у кого их несколько
К примеру если отсортировать по имени у 8 человека (Ava Garcia) есть 2 нфт (у некоторых их есть 6-8)

2023-06-26 05:17 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/Rating/RatingViewController.swift
> +    private let sortImageButton = UIButton()
поправил

2023-06-26 05:17 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/Rating/RatingViewController.swift
> +    @objc private func clickSort() {
поправил

2023-06-26 05:17 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/Rating/RatingViewController.swift
> +        let sortDialog = UIAlertController(title: "Сортировка", message: nil, preferredStyle: .actionSheet)
поправил

2023-06-26 05:18 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/Rating/RatingViewController.swift
> +        present(sortDialog, animated: true)
поправил

2023-06-26 05:20 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/Rating/RatingViewController.swift
> +        vc.userId = userId
поправил

2023-06-26 05:22 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/Rating/UserRatingCell.swift
> +class UserRatingCell: UITableViewCell, ReuseIdentifying {
+

2023-06-26 05:22 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/RatingProfile/RatingProfileViewController.swift
> +        nftCollectionLabel.text = "Коллекция NFT"
Локализация это не обязательный функционал для сдачи, предлагаю ей в следующем спринте заняться, если получится)

2023-06-26 05:23 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/RatingProfile/RatingProfileViewController.swift
> +    private let nftCollectionView = UIView()
+

2023-06-26 05:25 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/RatingProfile/RatingProfileViewController.swift
> +            nftCollectionCountLabel.bottomAnchor.constraint(equalTo: nftCollectionView.bottomAnchor, constant: -16),
поправил

2023-06-26 06:22 UTC, DmitriiMM commented on FakeNFT/Scenes /Statistic/RatingProfile/RatingProfileViewController.swift
> +            navigationController?.pushViewController(vc, animated: true)
Все все нашел)
спасибо)

2023-06-26 06:29 UTC, DmitriiMM approved these changes

2023-06-26 08:35 UTC, dmisuvorov approved these changes

2023-06-26 08:35 UTC, dmisuvorov commented on FakeNFT/Models/Network/Statistic/Nft.swift
> +}
Предложение: вынести из папки Statistics в отдельную папку, так как модель используется и в других пользовательских сценариях

2023-06-26 08:35 UTC, dmisuvorov commented on FakeNFT/Services/Statistic/NftService.swift
> +}
Предложение: вынести из папки Statistics в отдельную папку, так как запросы используются и в других пользовательских сценариях

2023-06-26 08:35 UTC, dmisuvorov commented on FakeNFT/Scenes /Statistic/ProfileCollection/ViewModel/ProfileCollectionViewModel.swift
> +
final
Пишут что с final будет быстрее при вызове функции находить адрес ячейки памяти, где лежит реализации вызванной функции.
https://habr.com/ru/post/673400/

2023-06-26 08:35 UTC, dmisuvorov commented on FakeNFT/Scenes /Statistic/Rating/ViewModel/RatingViewModel.swift
> +
final

2023-06-26 08:35 UTC, dmisuvorov commented on FakeNFT/Foundation/Observable.swift
> +    private var onChange: ((Value) -> Void)? = nil
Класс, спасибо что добавил!

2023-06-26 08:35 UTC, dmisuvorov commented on FakeNFT/Scenes /Statistic/ProfileCollection/NftCollectionCell.swift
> +            likeButton.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -15),
<img width="415" alt="Снимок экрана 2023-06-26 в 11 25 34" src="https://github.com/MaxCode2023/iOS-FakeNFT-StarterProject-Public/assets/26601585/f8de3046-6e02-42ab-a074-49579ef19c28">

Верстка лайка немного слетела на 14pro max, может брать констрейнт не от contentView ?

2023-06-26 08:55 UTC, MaxCode2023 commented on FakeNFT/Models/Network/Statistic/Nft.swift
> +}
Разбил по папкам User/Nft модельки, вынес из папки Statistics

2023-06-26 08:56 UTC, MaxCode2023 commented on FakeNFT/Services/Statistic/NftService.swift
> +}
Разбил по папкам User/Nft сервисы и реквесты, вынес из папки Statistics

2023-06-26 08:57 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/ProfileCollection/ViewModel/ProfileCollectionViewModel.swift
> +
добавил

2023-06-26 08:57 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/Rating/ViewModel/RatingViewModel.swift
> +
добавил

2023-06-26 09:02 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/ProfileCollection/NftCollectionCell.swift
> +            likeButton.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -15),
поправил

2023-06-28 07:54 UTC, Helvetii951 commented on FakeNFT/Scenes /Statistic/ProfileCollection/ProfileCollectionViewController.swift
> +        viewModel.getNftCollection(nftIdList: nftIds)
Лучше добавить во вью-модель Observable свойство вроде isLoading. А в контроллере уже использовать и показывать `ProgressHUD`

2023-06-28 07:54 UTC, Helvetii951 commented on FakeNFT/Scenes /Statistic/Rating/UserRatingCell.swift
> +    private let ratingScoreLabel = UILabel()
Повторюсь, в таких случаях лучше использовать ленивые свойства, о которых я писал выше.

2023-06-28 07:54 UTC, Helvetii951 commented on FakeNFT/Scenes /Statistic/Rating/UserRatingCell.swift
> +        configureViews()
![Uploading Снимок экрана 2023-06-28 в 12.18.21.png…]()
Делать эти действия нужно один раз. А то они будут выполняться каждый раз при переиспользовании.

2023-06-28 07:54 UTC, Helvetii951 commented on FakeNFT/Services/Nft/NftService.swift
> +}
Есть рекомендации по именованию протоколов. Название `NftService` выглядит, как конкретная реализация. И так пойдет, но на будущее скину статью:

[Нэйминг протоколов](https://www.swiftbysundell.com/articles/different-categories-of-swift-protocols/)

2023-06-28 16:25 UTC, MaxCode2023 commented on FakeNFT/DesignSystem/Colors.swift
> +    static let YPLightGrey = UIColor(named: "lightGrey") ?? .gray
+, обязательно попробую в будущем проекте)

2023-06-28 17:16 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/Rating/UserRatingCell.swift
> +        configureViews()
Исправил, также исправил в Nft Cell

2023-06-28 17:16 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/Rating/UserRatingCell.swift
> +    private let ratingScoreLabel = UILabel()
Заменил реализацию на ленивые свойства

2023-06-28 17:17 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/ProfileCollection/NftCollectionCell.swift
> +        }
исправил)

2023-06-28 17:23 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/ProfileCollection/ProfileCollectionViewController.swift
> +        viewModel.getNftCollection(nftIdList: nftIds)
Поменял на отдельное свойство

2023-06-28 17:26 UTC, MaxCode2023 commented on FakeNFT/Services/Nft/NftService.swift
> +}
Названия протоколов для сервисов скорректировал

2023-06-28 17:33 UTC, MaxCode2023 commented on FakeNFT/Scenes /Statistic/RatingProfile/ViewModel/RatingProfileViewModel.swift
> +    private let userService: UserService = UserServiceImpl()
Заменил на Constructor injection из статьи

2023-06-29 17:31 UTC, MaxCode2023 commented
Продублирую инфу о проекте здесь тоже)

Архитектура - MVVM
Верстка - Кодом
https://github.com/users/MaxCode2023/projects/1?pane=issue&itemId=31066798
[statitic_plan.md](https://github.com/MaxCode2023/iOS-FakeNFT-StarterProject-Public/files/11858703/statitic_plan.md)

Время планируемое/фактическое указал и в md файле и в проекте)

2023-06-29 17:31 UTC, MaxCode2023 commented
TabBar и базовый сториборд будет заменен для всех уже в общей develop ветке

2023-07-04 14:32 UTC, merged